language: node_js
node_js:
    - "node"
script:
    - yarn run build
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: dist
    target-branch: master
    on:
        branch: source
